### PR TITLE
Added class Test2

### PR DESCRIPTION
**Pull request by testerjames007**
Hi,

I have added Test2. Please review and approve.

Regards,
testerjames

### CODE REVIEW

**Comment by arminpashankar** [comment]
Go to merge to master. Please proceed.

Thanks,
Armin

**Review by arminpashankar — CHANGES_REQUESTED** [review]
Need some modification with std messages

**Comment by testerjames007** [comment]
Added std message as suggessted

**Comment by arminpashankar** [comment]
Good job buddy. Proceed with merge

**Comment by testerjames007** [comment]
Merged to master

**Review by arminpashankar — COMMENTED** [review]
push to master

**Pull request merged**
